@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package sakalti.swamplands.criterion;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
