name: フォルダの移動

on:
  push:
    branches:
      - 1.21  # または任意のブランチ

jobs:
  move-folder:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: フォルダに移動
        run: |
          echo "フォルダ 'a/b' を 'e/f' に移動しています..."
          
          # 移動元と移動先の指定
          src="src/main/java/quek/undergarden/"
          dest="src/main/java/sakalti/swawplands/"

          # 移動元フォルダが存在するか確認
          if [ -d "$src" ]; then
            # 移動先フォルダの親ディレクトリを作成
            mkdir -p "$(dirname "$dest")"

            # フォルダを移動
            mv "$src" "$dest"は
            echo "フォルダ移動完了: $src → $dest"
          else
            echo "フォルダ $src は存在しません。スキップします。"
          fi

      - name: 変更内容を確認
        run: |
          echo "変更されたファイル・フォルダ:"
          git status
          git diff

      - name: 変更をコミット
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "変更がないため、コミットをスキップします。"
            exit 0
          fi
          echo "変更をコミットします..."
          git commit -m "Move folder 'a/b' to 'e/f'"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
