name: パスの置き換え

on:
  push:
    branches:
      - 1.21  # または任意のブランチ

jobs:
  replace-path:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: パス内置き換え
        run: |
          # '含むすべてのファイルとディレクトリを検索
          find . -depth -name "*quek/undergarden*" | while read old_path; do
            # 新しいパスを作成
            new_path=$(echo "$old_path" | sed 's/quek\/undergarden/sakalti\/swamplands/g')
            
            # ディレクトリ名やファイル名を変更
            mv "$old_path" "$new_path"
          done

      - name: 変更をコミット
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Replace path"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
