name: パスの置き換え

on:
  push:
    branches:
      - 1.21 # まひたは任意のブランチ

jobs:
  replace-path:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: パス内の'a/b'を'e/f'に置き換え
        run: |
          # 'a/b' を含むすべてのファイルとディレクトリを検索
          find . -depth -name "*quek/undergraden*" | while read old_path; do
            # 新しいパスを作成
            new_path=$(echo "$old_path" | sed 's/quek\/undergarden/sakalti\/swamplands/g')
            
            # ディレクトリ名やファイル名を変更
            mv "$old_path" "$new_path"
          done

      - name: 変更内容を確認
        run: |
          git status
          git diff

      - name: 変更をコミット
        run: |
          git config --global user.name "saka"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "変更がないため、コミットをスキップします。"
            exit 0
          fi
          git commit -m "Replace path 'a/b' with 'e/f'"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
