name: パスの置き換え

on:
  push:
    branches:
      - 1.21  # または任意のブランチ

jobs:
  replace-path:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: 置き換え
        run: |
          echo "該当するパスを検索しています..."
          # 検索してパス名を置き換える
          find . -depth -path "*quek/undergarden*" | while read -r old_path; do
            # 新しいパス名を生成
            new_path=$(echo "$old_path" | sed 's|quek/undergarden|sakalti/swamplands|g')
            echo "リネーム中: $old_path → $new_path"
            
            # パスをリネーム
            mv "$old_path" "$new_path"
          done

      - name: 変更内容を確認
        run: |
          echo "変更されたファイル一覧:"
          git status
          git diff

      - name: 変更をコミット
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "変更がありません。コミットをスキップします。"
            exit 0
          fi
          echo "変更をコミットします..."
          git commit -m "Replace path 'a/b' with 'e/f'"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
