name: Rename file path

on:
  push:
    branches:
      - 1.21  # 変更を検出したいブランチを指定。例えば'main'や'master'など

jobs:
  rename-path:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rename file path
      run: |
        # フォルダ内のファイルを `a/b` から `e/f` に移動
        find a/b -type f -exec bash -c 'mv "$0" "${0/quek\/undergarden/sakalti\/swaplands}"' {} \;

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"   # 適当なユーザー名
        git config --global user.email "actions@github.com"  # 適当なメールアドレス

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.SECRETS_TOKEN }}  # GITHUB_TOKENを指定
      run: |
        git add .
        git commit -m "Rename file paths from a/b to e/f"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
