name: Rename file path

on:
  push:
    paths:
      - 'a/**'  # 変更したいパスのパターンを指定

jobs:
  rename-path:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rename file path
      run: |
        # フォルダ内のファイルを `a/b` から `e/f` に移動
        find a/b -type f -exec bash -c 'mv "$0" "${0/quek\/undergarden/sakalti\/swamplands}"' {} \;
    
    - name: Set up Git
      run: |
        git config --global user.name "saka"   # ユーザー名を設定
        git config --global user.email "saka@example.com"  # メールアドレスを設定

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKENを指定
      run: |
        git add .
        git commit -m "リネーム"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
